#!/usr/bin/env bash
#
# autofix_with_cline.sh <issue_number> — dispatch a filed bug (see
# error_watcher.py) to cline with deepseek/deepseek-v4-pro for an
# autonomous fix attempt: branch, let cline edit files agentically, commit,
# push, open a PR labeled auto-fix. Claude reviews and merges separately
# (see scripts/review_and_merge_autofix_prs.sh) — this script never merges
# anything itself.
#
# (2026-09-06: worker model swapped minimax-m3:free -> deepseek-v4-pro per
# the owner's delegation guideline — see scripts/offload.sh for the tier
# rationale. deepseek-v4-pro is cheap and far stronger at code than the
# old free model; --thinking low keeps the worker lean.)
#
# Usage: ./scripts/autofix_with_cline.sh <issue_number>
# Requires OPENROUTER_API_KEY in .env (see .env.example) and `gh` authenticated.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

REPO="GRITui/nevnew"
ISSUE_NUMBER="${1:?Usage: $0 <issue_number>}"

if [ -f "$PROJECT_ROOT/.env" ]; then
  # shellcheck disable=SC1091
  set -a
  source "$PROJECT_ROOT/.env"
  set +a
fi

if [ -z "${OPENROUTER_API_KEY:-}" ] || [ "$OPENROUTER_API_KEY" = "your-openrouter-api-key-here" ]; then
  echo "ERROR: OPENROUTER_API_KEY is not set in .env." >&2
  exit 1
fi

ISSUE_JSON="$(gh issue view "$ISSUE_NUMBER" --repo "$REPO" --json title,body)"
ISSUE_TITLE="$(echo "$ISSUE_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["title"])')"
ISSUE_BODY="$(echo "$ISSUE_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["body"])')"

BRANCH="autofix/issue-${ISSUE_NUMBER}"

# Always branch from latest main, never from whatever happened to be checked
# out (this script may run unattended back-to-back for multiple issues).
git fetch origin main
git checkout -B "$BRANCH" origin/main

PROMPT="Fix the bug described in nevnew issue #${ISSUE_NUMBER}.

Title: ${ISSUE_TITLE}

Body:
${ISSUE_BODY}

Make the smallest correct change that fixes this. Do not touch .env,
docker-compose.yml, setup.sh, or config.yaml's general_settings/master_key
block unless the bug is literally located in one of those files. Do not add
unrelated cleanup, refactors, or dependency changes. When done, the fix
should be complete and ready to review — don't leave partial/commented-out
attempts."

cline -P openrouter -k "$OPENROUTER_API_KEY" \
  -m deepseek/deepseek-v4-pro --thinking low --auto-approve true \
  -c "$PROJECT_ROOT" -t 600 "$PROMPT"

if [ -z "$(git status --porcelain)" ]; then
  echo "== no changes made by cline — commenting on issue, not opening a PR =="
  gh issue comment "$ISSUE_NUMBER" --repo "$REPO" --body \
    "Autofix attempt (minimax-m3:free via cline) made no changes — needs a human to look at this one."
  git checkout main
  git branch -D "$BRANCH"
  exit 0
fi

git add -A
git commit -m "fix(auto): ${ISSUE_TITLE} (#${ISSUE_NUMBER})

Autonomously generated by minimax-m3:free via cline.
Fixes #${ISSUE_NUMBER}."

git push -u origin "$BRANCH" --force-with-lease

gh pr create --repo "$REPO" \
  --base main --head "$BRANCH" \
  --title "fix(auto): ${ISSUE_TITLE} (#${ISSUE_NUMBER})" \
  --label auto-fix \
  --body "Fixes #${ISSUE_NUMBER}.

Autonomously generated by minimax-m3:free via cline — needs Claude review before merge."

echo "== opened autofix PR for issue #${ISSUE_NUMBER} =="
